# Generated by Django 5.0.3 on 2024-03-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_tags_lesson"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tags", new_name="Tag",),
    ]
